// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLZcQW01Gr7IXHLmSm8WiVHaMXvmEqsLY',
    appId: '1:840601767050:web:3cd4a4122ee485ebb1b173',
    messagingSenderId: '840601767050',
    projectId: 'signupapp-3b981',
    authDomain: 'signupapp-3b981.firebaseapp.com',
    storageBucket: 'signupapp-3b981.firebasestorage.app',
    measurementId: 'G-YPJKXXT75D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB95IL0KAhtckV-ziyoEr5RV9ljyxSl680',
    appId: '1:840601767050:android:2de6592463730cebb1b173',
    messagingSenderId: '840601767050',
    projectId: 'signupapp-3b981',
    storageBucket: 'signupapp-3b981.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaRpekA5VYX1pttvfZP6gO61kk0MgcHc0',
    appId: '1:840601767050:ios:8fce59fcb867f036b1b173',
    messagingSenderId: '840601767050',
    projectId: 'signupapp-3b981',
    storageBucket: 'signupapp-3b981.firebasestorage.app',
    iosBundleId: 'com.example.onlinemedical',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaRpekA5VYX1pttvfZP6gO61kk0MgcHc0',
    appId: '1:840601767050:ios:8fce59fcb867f036b1b173',
    messagingSenderId: '840601767050',
    projectId: 'signupapp-3b981',
    storageBucket: 'signupapp-3b981.firebasestorage.app',
    iosBundleId: 'com.example.onlinemedical',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLZcQW01Gr7IXHLmSm8WiVHaMXvmEqsLY',
    appId: '1:840601767050:web:7fe5aee1dc1e8e8db1b173',
    messagingSenderId: '840601767050',
    projectId: 'signupapp-3b981',
    authDomain: 'signupapp-3b981.firebaseapp.com',
    storageBucket: 'signupapp-3b981.firebasestorage.app',
    measurementId: 'G-P9Z2HLXVS1',
  );
}
